worker_processes auto;

events {
    worker_connections 256;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format main '$remote_addr - $host [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" "$http_user_agent"';
    access_log /var/log/nginx/access.log main;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name _;

        # Identify responses as coming from the origin.
        add_header X-Served-By "edgefabric-origin" always;
        add_header X-Origin-Server "demo-origin" always;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # CDN health-check endpoint.
        location = /healthz {
            access_log off;
            default_type text/plain;
            return 200 "OK\n";
        }
    }
}
